### ISSUE TITLE
Info - This EFI worked on 7810

### ISSUE THREAD

**Issue by markakash** [BillDH2k/Hackintosh-DELL-T5810-OpenCore#1]
Hey, just wanted to let you know you EFI works perfectly fine on Dell T7810 as well with following specs:
- Dual Intel Xeon E5-2680 v3
- Nvidia GT 710
- 64 gb DDR4 ram

Maybe you can add that in your README so that other 7810 users are also aware of it: :))

**Comment by thunfischente** [comment]
Wonderful bro, which case is better for Hackintosh between Dell T5810 and HP Z440?

**Comment by BillDH2k** [comment]
Z440 is more stable with macOS, including Sleep.

**Comment by thunfischente** [comment]
> Z440 is more stable with macOS, including Sleep.

thank you so much, I bough Z440 and it works perfectly, thanks for your EFI!
