### ISSUE TITLE
Issues after updating macos ventura to 13.3.1

### ISSUE THREAD

**Issue by jardasgit** [BillDH2k/Hackintosh-DELL-T5810-OpenCore#3]
Hi,

firstly thank you for your work! I use it almost without additional changes needed.

I recently tried updating the macos ventura to 13.2.1 and later to 13.3.1 but without success. It ends up rebooting to rescue mode. The update process almost finished, but the second boot is causing restart of the machine and switches to rescue mode.

I disabled the BlueToolFixup.kext prior the update as I found few mentions that this is a problematic driver, but still it did not help.

I also updated the OpenCore and used kexts to latest available versions, still no luck.

Unfortunately, I do not have opencore logs available or screenshot which would help here. The opencore debug log does not contain any error or suspicious entry. I might be reading it wrong though.

Any hint, suggestion would be much appreciated.

Thanks.

**Comment by BillDH2k** [comment]
What kind of Wifi device do you have? If you suspect that the wifi is causing the problem, try remove the wifi card and use wired internet to perform the upgrade first, then worry about the wifi driver later.

**Comment by jardasgit** [comment]
Thanks for your response!

I do not have a wifi card installed. It's the Dell T5810 with C610 chipset, AMD PCI video card installed, and couple of USB devices. Bluetooth token is plugged in as well, but I wouldn't expect it causing the problems, as the BlueToolFixup.kext is not loaded. Although, I guess, anything can happen.

I may try asking at the https://www.tonymacx86.com/threads/macos-13-3-1-update.325244/ forum as well.

Thanks.

**Comment by BillDH2k** [comment]
Try updating OC to latest 0.9.1 (recommend using OCAT tool). Or try my latest release which has OC 091. I've tested it on my T5810 and upgraded to Ventura 13.3.1 successfully (from 13.0).

**Comment by jardasgit** [comment]
Thank you for testing it and updating the code! I will test it with my configuration.

**Comment by BillDH2k** [comment]
No follow up response from OP. Assuming issue is closed.
