### ISSUE TITLE
Black screen after verbose

### ISSUE THREAD

**Issue by markakash** [BillDH2k/Hackintosh-DELL-T5810-OpenCore#4]
Hey, I was using your EFI on my Dell T7810 with Dual Xeon E5-2680v3 and 64gb 2100 MHz ram. I recently upgraded to Dual Xeon E5-2680v4 and 128gb 2400MHz ram. When I try to boot into the installer, after the whole verbose logs/message passing on the screen I get black screen. The PC is still up and running but I don't see the installer or any other error messages. I tried HDMI and Display Port both resulted in same result. I updated the Cpuid1Data to incorporate for v4 CPU and also did the BIOS trick you mentioned. Do you have any other ideas what might be causing it? I m using AMD Radeon RX 6600XT which is officially supported in MacOS.

I have attached OpenCore logs below

Any help is appreciated. :))

[opencore-2023-05-06-111043.txt](https://github.com/BillDH2k/Hackintosh-DELL-T5810-OpenCore/files/11412186/opencore-2023-05-06-111043.txt)

**Comment by BillDH2k** [comment]
Have you tried to add "agdpmod=pikera" to boot-args?

**Comment by PepeCortizona** [comment]
How are you, look, I have an extremely stable EFI, the Slepp and Wakeup works perfectly, but when you use the Sleep about 5 or 8 times, the computer hangs or reset
[EFI.zip](https://github.com/BillDH2k/Hackintosh-DELL-T5810-OpenCore/files/13467901/EFI.zip)

Maybe you can check the EFI and serve you, since I see that you do not work the Slepp and Wakeup

**Comment by BillDH2k** [comment]
Are you running Big Sur? That's the only version, I've found with the help of VoodooTSCsync.text, that sleep can work (most of the time).

**Comment by PepeCortizona** [comment]
Yes I am running Big Sur
I dint now if works on newer systems 
Do you test in Sonoma, Ventura or Monterey ?
Do you now if is possible run Sonoma, Ventura or Monterey with E5-V3  or need V4 CPUs ?

**Comment by BillDH2k** [comment]
Try my latest EFI release. It supports Sonoma.

**Comment by BillDH2k** [comment]
Closed this issue assuming the OP has resolved the issue already.
