### ISSUE TITLE
T5810 Installation Fail: OCB:StartImage failed - Aborted

### ISSUE THREAD

**Issue by ianLi233** [BillDH2k/Hackintosh-DELL-T5810-OpenCore#6]
https://dortania.github.io/OpenCore-Install-Guide/installer-guide/windows-install.html 
I followed this guide and your installation guide, but  OCB:StartImage failed - Aborted is all I got.
Any help is Appreciated, thanks!

**Comment by BillDH2k** [comment]
Make sure you updated to A32 or A33 BIOS first. Then, trying to toggle  [Memory Map I/O ABove 4G], and/or, in combination of toggling [Enable Legacy Option ROMs] (assuming you video card has an UEFI compatible BIOS ). Anyway, the trick to force the BIOS to re-initialize. That's how I did to overcome exactly the same issue. This Dell machine's BIOS is very sensitive, but it should work once you pass the booting.

**Comment by ianLi233** [comment]
Yeah, So my bios is at A34 right now, this might be the issue.

**Comment by BillDH2k** [comment]
I haven't tried A34 yet. If you could down grade to A32 (I saw A33 no longer available from Dell site), try again.

Here was the trail of what I did previously to overcome this booting issue (including BIOS settings), [here](https://github.com/NOTNlCE/Dell-Precision-T5810-OpenCore/issues/2#issue-1202227764).

**Comment by ianLi233** [comment]
OK, I'll let you know my outcomes.

**Comment by ianLi233** [comment]
OMG, It worked! Thank You! One other thing, does this efi supports upgrading to Sonoma Natively?

**Comment by BillDH2k** [comment]
I believe it needs some work to fixe a few things. But I haven't had the time to investigate. Ventura/Monterey are running very stable right now for me.  I will try to give it a shot during the holiday.

**Comment by ianLi233** [comment]
Much appreciated!!! Thank you for your contributions!!!

**Comment by BillDH2k** [comment]
@Gear-dev-sudo Added support for Sonoma.

**Comment by ianLi233** [comment]
You ARE A LEGEND!

**Comment by PepeCortizona** [comment]
> I haven't tried A34 yet. If you could down grade to A32 (I saw A33 no longer available from Dell site), try again.
> 
> Here was the trail of what I did previously to overcome this booting issue (including BIOS settings), [here](https://github.com/NOTNlCE/Dell-Precision-T5810-OpenCore/issues/2#issue-1202227764).

Try this links for T5810 A32 and A33 bios
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=57fj7&oscode=w764&productcode=precision-t5810-workstation
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=r7jn2&oscode=w764&productcode=precision-t5810-workstation

Try this links for T7810 A32 and A33 bios
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=r7hv6&oscode=w764&productcode=precision-t7810-workstation
https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=wctj4&oscode=w764&productcode=precision-t7810-workstation
