### ISSUE TITLE
Precision T7610 modifications

### ISSUE THREAD

**Issue by PepeCortizona** [BillDH2k/Hackintosh-DELL-T5810-OpenCore#7]
Maybe is a stupid question, but, is I ant o use your EFI in a T7610, what I will nee to modificative ?
if is possible advice me please

**Comment by PepeCortizona** [comment]
I have this EFI that works fine  With BigSur, but I have "in memory panic stackshot succeeded ** bytes traced 1668" error when try to install Sonoma
[EFI.zip](https://github.com/BillDH2k/Hackintosh-DELL-T5810-OpenCore/files/13806444/EFI.zip)

**Comment by BillDH2k** [comment]
Unfortunately, T5610/7610 (X79 system, not X99 like T5810) is known to experience booting issue (TSC out of sync) for Monterey and beyond. No fix is found at the moment.

**Comment by BillDH2k** [comment]
Here is the link to the [related thread](https://www.insanelymac.com/forum/topic/341600-success-huananzhi-x79-zd3-xeon-e5-2689-mojave-10146-big-sur-1123-monterey-1201-sonoma-beta-7/?do=findComment&comment=2796539).

**Comment by PepeCortizona** [comment]
Thanks
Is a sad reality
